run-name: hello
on: [push]
env:
  HHo: ${{ vars.HELLO_AAM }}
  HO: ${{ secrets.ALO_HAMOSH }}
jobs:
  output-variables:
    runs-on: ubuntu-latest
    steps:
      - run: echo "$HHo"
        env:
          ALO_HAMOSH: ${{vars.ALO_HAMOSH}}
          Baby: Hello
      - run: echo "$HO"
