name: "download artifact"

run-name: ${{ github.actor }} is downloading file

on: [push]

jobs:
  download-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: downlaod file
        uses: actions/download-artifact@v3
        with:
          name: output-log-file
