run-name: ${{ github.actor }}
on: [push]

jobs:
  testing-contexts:
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest

    steps:
      - run: echo "commiting to $GITHUB_REF"
